management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

      file-services-root: /file

server:
  port: 8080

spring:
  application:
    name: MSAssignment

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

storage:
  location: storage
